{
  imports = [
    ./telescope.nix
    ./treesitter.nix
    ./neogit.nix
    ./neocord.nix
    ./conform.nix
    ./autoclose.nix
    ./glow.nix
    ./hex.nix
    ./instant.nix
    ./avante.nix
    ./goyo.nix
    ./wrapping.nix
    ./jupytext.nix
    ./lsp.nix
    ./typst.nix
  ];
}
